# Use postgres/example user/password credentials
version: '3.1'

services:

  location-db:
    image: postgres
    restart: always
    ports:
      - "32768:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: locations

# Uncomment next lines to add adminer database manager.
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8081:8080"

volumes:
  db-data:
    driver: local
